package colr

import "testing"

// Clearly not a real test - just a visual reference
func TestOutput(t *testing.T) {
	t.Run("Visual test", func(t *testing.T) {
		// Special
		print(Bold("hello!"))
		print(Dim("hello!"))
		print(Italic("hello!"))
		print(Underline("hello!"))
		print(Blink("hello!"))
		print(Strikethrough("hello!"))

		// Text colors
		print(Black("hello!"))
		print(Red("hello!"))
		print(Green("hello!"))
		print(Yellow("hello!"))
		print(Blue("hello!"))
		print(Purple("hello!"))
		print(Cyan("hello!"))
		print(Gray("hello!"))
		print(White("hello!"))

		// back colors
		print(OnBlack("hello!"))
		print(OnRed("hello!"))
		print(OnGreen("hello!"))
		print(OnYellow("hello!"))
		print(OnBlue("hello!"))
		print(OnPurple("hello!"))
		print(OnCyan("hello!"))
		print(OnGray("hello!"))
		print(OnWhite("hello!"))

		// .. or combined
		print(BlackOnBlack("hello!"))
		print(BlackOnRed("hello!"))
		print(BlackOnGreen("hello!"))
		print(BlackOnYellow("hello!"))
		print(BlackOnBlue("hello!"))
		print(BlackOnPurple("hello!"))
		print(BlackOnCyan("hello!"))
		print(BlackOnGray("hello!"))
		print(BlackOnWhite("hello!"))
		print(RedOnBlack("hello!"))
		print(RedOnRed("hello!"))
		print(RedOnGreen("hello!"))
		print(RedOnYellow("hello!"))
		print(RedOnBlue("hello!"))
		print(RedOnPurple("hello!"))
		print(RedOnCyan("hello!"))
		print(RedOnGray("hello!"))
		print(RedOnWhite("hello!"))
		print(GreenOnBlack("hello!"))
		print(GreenOnRed("hello!"))
		print(GreenOnGreen("hello!"))
		print(GreenOnYellow("hello!"))
		print(GreenOnBlue("hello!"))
		print(GreenOnPurple("hello!"))
		print(GreenOnCyan("hello!"))
		print(GreenOnGray("hello!"))
		print(GreenOnWhite("hello!"))
		print(YellowOnBlack("hello!"))
		print(YellowOnRed("hello!"))
		print(YellowOnGreen("hello!"))
		print(YellowOnYellow("hello!"))
		print(YellowOnBlue("hello!"))
		print(YellowOnPurple("hello!"))
		print(YellowOnCyan("hello!"))
		print(YellowOnGray("hello!"))
		print(YellowOnWhite("hello!"))
		print(BlueOnBlack("hello!"))
		print(BlueOnRed("hello!"))
		print(BlueOnGreen("hello!"))
		print(BlueOnYellow("hello!"))
		print(BlueOnBlue("hello!"))
		print(BlueOnPurple("hello!"))
		print(BlueOnCyan("hello!"))
		print(BlueOnGray("hello!"))
		print(BlueOnWhite("hello!"))
		print(PurpleOnBlack("hello!"))
		print(PurpleOnRed("hello!"))
		print(PurpleOnGreen("hello!"))
		print(PurpleOnYellow("hello!"))
		print(PurpleOnBlue("hello!"))
		print(PurpleOnPurple("hello!"))
		print(PurpleOnCyan("hello!"))
		print(PurpleOnGray("hello!"))
		print(PurpleOnWhite("hello!"))
		print(CyanOnBlack("hello!"))
		print(CyanOnRed("hello!"))
		print(CyanOnGreen("hello!"))
		print(CyanOnYellow("hello!"))
		print(CyanOnBlue("hello!"))
		print(CyanOnPurple("hello!"))
		print(CyanOnCyan("hello!"))
		print(CyanOnGray("hello!"))
		print(CyanOnWhite("hello!"))
		print(GrayOnBlack("hello!"))
		print(GrayOnRed("hello!"))
		print(GrayOnGreen("hello!"))
		print(GrayOnYellow("hello!"))
		print(GrayOnBlue("hello!"))
		print(GrayOnPurple("hello!"))
		print(GrayOnCyan("hello!"))
		print(GrayOnGray("hello!"))
		print(GrayOnWhite("hello!"))
		print(WhiteOnBlack("hello!"))
		print(WhiteOnRed("hello!"))
		print(WhiteOnGreen("hello!"))
		print(WhiteOnYellow("hello!"))
		print(WhiteOnBlue("hello!"))
		print(WhiteOnPurple("hello!"))
		print(WhiteOnCyan("hello!"))
		print(WhiteOnGray("hello!"))
		print(WhiteOnWhite("hello!"))
	})
}
